apiVersion: v1
kind: Service
metadata:
  name: app-v1-service
  labels:
    app: app-v1
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: app-v1-deployment
