apiVersion: v1
kind: Service
metadata:
  name: app-v2-service
  labels:
    app: app-v2
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      name: http
  selector:
    app: app-v2-deployment
